### ISSUE TITLE
404 - Invalid request

### ISSUE THREAD

**Issue by Jirka1111** [PrimeHammer/gopay-ruby#4]
Zdravím,
je gem aktuální? Nějak se s ním nemůžu domluvit, resp. vždy se mi v konzoli vrátí stejná chyba:

GoPay::Error: 404 : {"date_issued"=>"2017-04-27T01:19:31.742+0200", "errors"=>[{"scope"=>"G", "error_code"=>116, "error_name"=>"INVALID_REQUEST", "message"=>"Invalid request"}]}

Request jsem zkusil použít jak z readme, tak ze stránek GoPay.

**Comment by dayweek** [comment]
Hi @Jirka1111 , we have the gem in production and it works. Do you still experience the problem? If you do, what method did you call?

**Comment by Jirka1111** [comment]
Hi @dayweek No, the gem works great. The problem was with setting Gopay url. It should be like this:

config.gate = "https://gw.sandbox.gopay.com"

or (in production)

config.gate = "https://gate.gopay.cz"

So no setting specific url in config file - my bad.

Thanks for a great job ;)

**Comment by dayweek** [comment]
@Jirka1111 ok, sounds good:) closing the ticket.
