### ISSUE TITLE
uninitialized constant GoPay::Gateway

### ISSUE THREAD

**Issue by richardrails** [PrimeHammer/gopay-ruby#9]
I get error 
`uninitialized constant GoPay::Gateway`
when I want to create gateway. 

Gemfile:
gem 'rails', '~> 5.1.6.1'
gem 'gopay-ruby', require: 'gopay'

could you help me please?

**Comment by richardrails** [comment]
module Gateway is not loaded because it is in lib, not in app?

**Comment by dayweek** [comment]
Probably using an older version of the gem where GoPay::Gateway is not available.
